<a href="https://colab.research.google.com/github/WhosLupe/THC_MancillaLagunaJorgeGuadalupe/blob/main/24_de_octubre_de_2023_MancillaLagunaJorgeGuadalupe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
"""

Ejercicio de clase 24 de octubre de 2023#

Nombre del programa: 24 de octubre de 2023_MancillaLagunaJorgeGuadalupe.ipynb

"""

import numpy as np
arr = np.array([1, 2, 3])
print(arr[0])

1


In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [6]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [7]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:4])

[1 2 3 4]


In [8]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[-3:-1])

[5 6]


In [9]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5:2])
#el tercero es el paso

[2 4]


In [10]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::2])

[1 3 5 7]


In [12]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::1])

[1 2 3 4 5 6 7]


In [13]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[:0])

[]


In [14]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[0:])

[1 2 3 4 5 6 7]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[::0])

In [20]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1,1:4])

[7 8 9]


In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,2])

In [ ]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, :])

In [21]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[0:2,1:4])

[[2 3 4]
 [7 8 9]]


In [24]:
arr = np.array([41, 42, 43, 44])
filter_arr = arr > 42
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False False  True  True]
[43 44]


In [27]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resta=x-y
print(f"loa suma es{resta}")

loa suma es[-3 -3 -3]


In [31]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resta=x+y
print(f"loa suma es{resta}")

loa suma es[5 7 9]


In [32]:
print(f"num pi= {np.pi}")


num pi= 3.141592653589793


In [33]:
angulos=np.array([0, np.pi/2,np.pi])
seno=np.sin(angulos)
print(f"los senos{seno}")
print(f"delos angulos{angulos}")

los senos[0.0000000e+00 1.0000000e+00 1.2246468e-16]
delos angulos[0.         1.57079633 3.14159265]


In [44]:
x.reshape(-1,1).shape


(2, 1)

In [48]:
arreglo=np.array([1, 11])
hola=0
num=input("numero: ")
while hola != num:
  hola=np.random.randint(1,11,5)
  print(f"tu numero es:{hola} ?")
  if hola != num:
    print("no :/")
  else:
    print("ye")

numero: 3
tu numero es:[5 4 2 6 8] ?
no :/
tu numero es:[ 6  9  5  7 10] ?
no :/
tu numero es:[6 1 1 1 3] ?
no :/
tu numero es:[4 8 8 5 5] ?
no :/
tu numero es:[4 5 5 3 2] ?
no :/
tu numero es:[ 3  9 10  7  7] ?
no :/
tu numero es:[ 3  6  9  3 10] ?
no :/
tu numero es:[4 8 4 5 6] ?
no :/
tu numero es:[2 8 6 6 5] ?
no :/
tu numero es:[10  7  4  5 10] ?
no :/
tu numero es:[6 2 1 4 3] ?
no :/
tu numero es:[8 2 8 1 2] ?
no :/
tu numero es:[2 4 7 5 8] ?
no :/
tu numero es:[7 9 9 9 6] ?
no :/
tu numero es:[3 1 1 1 1] ?
no :/
tu numero es:[9 8 4 7 6] ?
no :/
tu numero es:[3 3 8 8 2] ?
no :/
tu numero es:[ 6  2  9 10  5] ?
no :/
tu numero es:[6 6 1 2 8] ?
no :/
tu numero es:[9 7 7 9 1] ?
no :/
tu numero es:[ 8  6 10  8  7] ?
no :/
tu numero es:[6 5 5 2 6] ?
no :/
tu numero es:[7 3 7 5 6] ?
no :/
tu numero es:[7 3 1 9 1] ?
no :/
tu numero es:[6 2 7 2 5] ?
no :/
tu numero es:[ 9 10  8  9 10] ?
no :/
tu numero es:[ 4  3 10  6  2] ?
no :/
tu numero es:[7 2 5 9 6] ?
no :/
tu numero es:[1 3 7 7 8] ?

<ipython-input-48-81c4d84e100d>:7: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  if hola != num:
<ipython-input-48-81c4d84e100d>:4: FutureWarning: elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
  while hola != num:


Se han truncado las últimas 5000 líneas del flujo de salida.
no :/
tu numero es:[1 8 9 8 3] ?
no :/
tu numero es:[5 4 8 5 6] ?
no :/
tu numero es:[5 9 9 6 2] ?
no :/
tu numero es:[ 1  8  2  3 10] ?
no :/
tu numero es:[6 6 4 2 7] ?
no :/
tu numero es:[10  3  9  2  9] ?
no :/
tu numero es:[3 1 3 1 4] ?
no :/
tu numero es:[6 2 4 3 3] ?
no :/
tu numero es:[7 4 4 5 4] ?
no :/
tu numero es:[2 3 8 1 6] ?
no :/
tu numero es:[6 3 9 3 5] ?
no :/
tu numero es:[ 7  4 10  3  9] ?
no :/
tu numero es:[ 5 10  5 10  6] ?
no :/
tu numero es:[7 5 9 7 1] ?
no :/
tu numero es:[ 3  4  6 10  8] ?
no :/
tu numero es:[3 6 6 1 8] ?
no :/
tu numero es:[3 1 4 6 4] ?
no :/
tu numero es:[4 4 7 1 4] ?
no :/
tu numero es:[6 1 3 4 6] ?
no :/
tu numero es:[ 3 10  6  9  1] ?
no :/
tu numero es:[2 3 9 9 4] ?
no :/
tu numero es:[ 4  7  3  9 10] ?
no :/
tu numero es:[1 2 7 1 5] ?
no :/
tu numero es:[ 1  4  5  3 10] ?
no :/
tu numero es:[6 7 7 2 3] ?
no :/
tu numero es:[5 6 4 3 7] ?
no :/
tu numero es:[7 3 1 1 5] ?
no :/
tu

KeyboardInterrupt: ignored

In [40]:
x=np.linspace(0,1,2)
x

array([0., 1.])

In [41]:
np.random.uniform(0,1,6)

array([0.91179569, 0.86974966, 0.72225664, 0.64252771, 0.02049619,
       0.25936295])

In [30]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resta=x/y
print(f"loa suma es{resta}")

loa suma es[0.25 0.4  0.5 ]


In [29]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resta=x*y
print(f"loa suma es{resta}")

loa suma es[ 4 10 18]


In [28]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
resta=x%y
print(f"loa suma es{resta}")

loa suma es[1 2 3]


In [23]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
filter_arr = arr % 2 == 0
newarr = arr[filter_arr]
print(filter_arr)
print(newarr)

[False  True False  True False  True False]
[2 4 6]
